### ISSUE TITLE
Add main image / illustration to article template

### ISSUE THREAD

**Issue by tobie** [unlockopen/www.unlockopen.com-v4#6]
- [x] Implement hero image display in the article template.
- [x] It should be possible to link the image in the front-matter
- [x] I should be possible to add optional image credits in the front-matter (needs to support inline markdown in case links are required by the licensing terms)
- [x] It should be possible to add a legend to the image (also supporting inline markdown)

**Comment by madrilene** [comment]
The sharable image will be generated using the article title and other items, like your image, the website's title, or a custom image. 
As the title would be displayed double I don't think it makes sense using that same image as a featured image, but we could try. Otherwise I'd display just the image you set in the front matter, and also use that image as a section of the sharable image.

**Comment by tobie** [comment]
This issue is not about the shareable image, but about a hero image in the article section. (We're discussing the OGP images in #14).
